### PR TITLE
Fixes an issue with dark modes, where observation "hi/Lo" color values (if specified) in skin.conf are not honored.

### PR DESCRIPTION
**Pull request by W0CHP**
Noticed that in dark mode, the "hi/lo" colors if defined in `skin.conf` are not honored/rendered. This minor PR fixes that.

### CODE REVIEW

**Comment by Pogs2004** [comment]
I noticed this the other day. I have updated the style.min.css but still not seeing any difference - is the sccs file just used for building or should it go somewhere?

**Comment by Pogs2004** [comment]
I would suggest changing the default lo_value_color in skin.conf to #4b94eb which can be read easily in both light and dark modes:

```
        # Here you can set a hex code for the text color of low / high values
        # on all cards. By default they are grey. (quotes are needed on values)
        # lo_value_color = "#03a9f4"
        # hi_value_color = "#f44336"
        lo_value_color = "#4b94eb"
        hi_value_color = red

```

**Review by Pogs2004 — CHANGES_REQUESTED** [review]
The default lo_value_color = blue does not look good in dark mode. Suggest changing skin.conf appearance section to:

```
        # Here you can set a hex code for the text color of low / high values
        # on all cards. By default they are grey. (quotes are needed on values)
        # lo_value_color = "#03a9f4"
        # hi_value_color = "#f44336"
        lo_value_color = "#4b94eb"
        hi_value_color = red
```
See review comments.

**Comment by Pogs2004** [comment]
I'm struggling a bit with Github, it's not a platform I am very familiar with. There are two forks that have had recent activity, @W0CHP and @seehase, are these being merged? I am currently working on code for an interactive sun path diagram that gets the date, time and location from Weewx, when complete how do I get this on Github, do I create a new fork?

**Review by seehausen — APPROVED** [review]

**Comment by seehausen** [comment]
@Pogs2004 as in the original repo there is not much activity we want to continue working in this fork here.
everything from @W0CHP is already included and merged

**Comment by W0CHP** [comment]
> The default lo_value_color = blue does not look good in dark mode. Suggest changing skin.conf appearance section to:
> 
> ```
>         # Here you can set a hex code for the text color of low / high values
>         # on all cards. By default they are grey. (quotes are needed on values)
>         # lo_value_color = "#03a9f4"
>         # hi_value_color = "#f44336"
>         lo_value_color = "#4b94eb"
>         hi_value_color = red
> ```
> 
> See review comments.

Please enter a new PR for this. As this PR fixes a bug (vs. styling tweaks). Thanks!

**Comment by W0CHP** [comment]
> @Pogs2004 as in the original repo there is not much activity we want to continue working in this fork here. everything from @W0CHP is already included and merged

I agree with @seehausen 
I am using @seehausen's fork as "authoritative". My fork is simply for the changes I make and propose, then merge into this one ;-)

**Pull request merged**
