### PR TITLE
Fixed issue #11 wrong date in header

### PR DESCRIPTION
**Pull request by seehase**
Adapted code from #11

### CODE REVIEW

**Review by W0CHP — APPROVED** [review]

**Comment by seehausen** [comment]
There is still a small bug... I'll work on it
on the sub pages the date is still show
https://solar.seehausen.org/weewx/year-2019.html
or https://solar.seehausen.org/weewx/month-2019-01.html
but not on https://solar.seehausen.org/weewx/year-2022.html

I see that `#attr $active_nav = 'archive'` is set but not yet working.... please hold on ;-)

**Comment by W0CHP** [comment]
Ensure that you stop weeex, delete all of the rendered HTML, and then regenerate them with wee_report (and then restart weeex). I ran into the same issue a long time ago. :)
Or maybe you already have done that and there is a bug :-(

**Comment by seehausen** [comment]
Ah that's right... I was not aware that not all files are always generated, thanks @W0CHP

**Review by Pogs2004 — COMMENTED** [review]
Works fine for me.

**Comment by Pogs2004** [comment]
I always thought that once inside the archives navigation wasn't very good, the only way to get back to, say the year xx main report from a specific month was to use the browsers back button or click on the Reports (archive) link to go back to the top level, all well and good but on the IOS app version (which I use) there are no browser navigation links, just swiping.

I have used the empty space where N/A was to provide a link back to the previous page. Currently working on some code so it shows the name of the page it will take you back to (i.e. Return to 2021), and to exclude it from archive.html. Also need to tidy it up a bit, at the moment if you enter the site directly to one of the year or month reports the link will take you back to where you came from.

See here: https://www.360shetland.co.uk/weather/archive.html

**Pull request merged**
